// Code generated by mockery v2.53.6. DO NOT EDIT.

package handlers

import (
	context "context"
	filters "shb/internal/repositories/filters"

	mock "github.com/stretchr/testify/mock"

	models "shb/internal/models"

	smsProvider "shb/pkg/external/sms/smsProvider"
)

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// ApproveBooking provides a mock function with given fields: ctx, bookingID, institutionUserID
func (_m *MockIService) ApproveBooking(ctx context.Context, bookingID int, institutionUserID int) error {
	ret := _m.Called(ctx, bookingID, institutionUserID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, bookingID, institutionUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_ApproveBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveBooking'
type MockIService_ApproveBooking_Call struct {
	*mock.Call
}

// ApproveBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - institutionUserID int
func (_e *MockIService_Expecter) ApproveBooking(ctx interface{}, bookingID interface{}, institutionUserID interface{}) *MockIService_ApproveBooking_Call {
	return &MockIService_ApproveBooking_Call{Call: _e.mock.On("ApproveBooking", ctx, bookingID, institutionUserID)}
}

func (_c *MockIService_ApproveBooking_Call) Run(run func(ctx context.Context, bookingID int, institutionUserID int)) *MockIService_ApproveBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_ApproveBooking_Call) Return(_a0 error) *MockIService_ApproveBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_ApproveBooking_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_ApproveBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ApproveEvent provides a mock function with given fields: ctx, eventID
func (_m *MockIService) ApproveEvent(ctx context.Context, eventID int) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for ApproveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_ApproveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveEvent'
type MockIService_ApproveEvent_Call struct {
	*mock.Call
}

// ApproveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int
func (_e *MockIService_Expecter) ApproveEvent(ctx interface{}, eventID interface{}) *MockIService_ApproveEvent_Call {
	return &MockIService_ApproveEvent_Call{Call: _e.mock.On("ApproveEvent", ctx, eventID)}
}

func (_c *MockIService_ApproveEvent_Call) Run(run func(ctx context.Context, eventID int)) *MockIService_ApproveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_ApproveEvent_Call) Return(_a0 error) *MockIService_ApproveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_ApproveEvent_Call) RunAndReturn(run func(context.Context, int) error) *MockIService_ApproveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CancelMyBooking provides a mock function with given fields: ctx, bookingID, userID
func (_m *MockIService) CancelMyBooking(ctx context.Context, bookingID int, userID int) error {
	ret := _m.Called(ctx, bookingID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CancelMyBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, bookingID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_CancelMyBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelMyBooking'
type MockIService_CancelMyBooking_Call struct {
	*mock.Call
}

// CancelMyBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - userID int
func (_e *MockIService_Expecter) CancelMyBooking(ctx interface{}, bookingID interface{}, userID interface{}) *MockIService_CancelMyBooking_Call {
	return &MockIService_CancelMyBooking_Call{Call: _e.mock.On("CancelMyBooking", ctx, bookingID, userID)}
}

func (_c *MockIService_CancelMyBooking_Call) Run(run func(ctx context.Context, bookingID int, userID int)) *MockIService_CancelMyBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_CancelMyBooking_Call) Return(_a0 error) *MockIService_CancelMyBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_CancelMyBooking_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_CancelMyBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CheckSMSBalance provides a mock function with given fields: ctx
func (_m *MockIService) CheckSMSBalance(ctx context.Context) (*smsProvider.BalanceResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckSMSBalance")
	}

	var r0 *smsProvider.BalanceResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*smsProvider.BalanceResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *smsProvider.BalanceResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*smsProvider.BalanceResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_CheckSMSBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckSMSBalance'
type MockIService_CheckSMSBalance_Call struct {
	*mock.Call
}

// CheckSMSBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) CheckSMSBalance(ctx interface{}) *MockIService_CheckSMSBalance_Call {
	return &MockIService_CheckSMSBalance_Call{Call: _e.mock.On("CheckSMSBalance", ctx)}
}

func (_c *MockIService_CheckSMSBalance_Call) Run(run func(ctx context.Context)) *MockIService_CheckSMSBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIService_CheckSMSBalance_Call) Return(_a0 *smsProvider.BalanceResult, _a1 error) *MockIService_CheckSMSBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_CheckSMSBalance_Call) RunAndReturn(run func(context.Context) (*smsProvider.BalanceResult, error)) *MockIService_CheckSMSBalance_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteBooking provides a mock function with given fields: ctx, bookingID, institutionUserID
func (_m *MockIService) CompleteBooking(ctx context.Context, bookingID int, institutionUserID int) error {
	ret := _m.Called(ctx, bookingID, institutionUserID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, bookingID, institutionUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_CompleteBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteBooking'
type MockIService_CompleteBooking_Call struct {
	*mock.Call
}

// CompleteBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - institutionUserID int
func (_e *MockIService_Expecter) CompleteBooking(ctx interface{}, bookingID interface{}, institutionUserID interface{}) *MockIService_CompleteBooking_Call {
	return &MockIService_CompleteBooking_Call{Call: _e.mock.On("CompleteBooking", ctx, bookingID, institutionUserID)}
}

func (_c *MockIService_CompleteBooking_Call) Run(run func(ctx context.Context, bookingID int, institutionUserID int)) *MockIService_CompleteBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_CompleteBooking_Call) Return(_a0 error) *MockIService_CompleteBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_CompleteBooking_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_CompleteBooking_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmOTP provides a mock function with given fields: ctx, phone, otp
func (_m *MockIService) ConfirmOTP(ctx context.Context, phone string, otp string) (*models.TokenResponse, error) {
	ret := _m.Called(ctx, phone, otp)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmOTP")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.TokenResponse, error)); ok {
		return rf(ctx, phone, otp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.TokenResponse); ok {
		r0 = rf(ctx, phone, otp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, phone, otp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_ConfirmOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmOTP'
type MockIService_ConfirmOTP_Call struct {
	*mock.Call
}

// ConfirmOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - otp string
func (_e *MockIService_Expecter) ConfirmOTP(ctx interface{}, phone interface{}, otp interface{}) *MockIService_ConfirmOTP_Call {
	return &MockIService_ConfirmOTP_Call{Call: _e.mock.On("ConfirmOTP", ctx, phone, otp)}
}

func (_c *MockIService_ConfirmOTP_Call) Run(run func(ctx context.Context, phone string, otp string)) *MockIService_ConfirmOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIService_ConfirmOTP_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockIService_ConfirmOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_ConfirmOTP_Call) RunAndReturn(run func(context.Context, string, string) (*models.TokenResponse, error)) *MockIService_ConfirmOTP_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBooking provides a mock function with given fields: ctx, userID, needID, quantity, note
func (_m *MockIService) CreateBooking(ctx context.Context, userID int, needID int, quantity float64, note string) (int, error) {
	ret := _m.Called(ctx, userID, needID, quantity, note)

	if len(ret) == 0 {
		panic("no return value specified for CreateBooking")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, float64, string) (int, error)); ok {
		return rf(ctx, userID, needID, quantity, note)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, float64, string) int); ok {
		r0 = rf(ctx, userID, needID, quantity, note)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, float64, string) error); ok {
		r1 = rf(ctx, userID, needID, quantity, note)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_CreateBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBooking'
type MockIService_CreateBooking_Call struct {
	*mock.Call
}

// CreateBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - needID int
//   - quantity float64
//   - note string
func (_e *MockIService_Expecter) CreateBooking(ctx interface{}, userID interface{}, needID interface{}, quantity interface{}, note interface{}) *MockIService_CreateBooking_Call {
	return &MockIService_CreateBooking_Call{Call: _e.mock.On("CreateBooking", ctx, userID, needID, quantity, note)}
}

func (_c *MockIService_CreateBooking_Call) Run(run func(ctx context.Context, userID int, needID int, quantity float64, note string)) *MockIService_CreateBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(float64), args[4].(string))
	})
	return _c
}

func (_c *MockIService_CreateBooking_Call) Return(_a0 int, _a1 error) *MockIService_CreateBooking_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_CreateBooking_Call) RunAndReturn(run func(context.Context, int, int, float64, string) (int, error)) *MockIService_CreateBooking_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEvent provides a mock function with given fields: ctx, e
func (_m *MockIService) CreateEvent(ctx context.Context, e *models.Event) (int, error) {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Event) (int, error)); ok {
		return rf(ctx, e)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Event) int); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Event) error); ok {
		r1 = rf(ctx, e)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_CreateEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEvent'
type MockIService_CreateEvent_Call struct {
	*mock.Call
}

// CreateEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - e *models.Event
func (_e *MockIService_Expecter) CreateEvent(ctx interface{}, e interface{}) *MockIService_CreateEvent_Call {
	return &MockIService_CreateEvent_Call{Call: _e.mock.On("CreateEvent", ctx, e)}
}

func (_c *MockIService_CreateEvent_Call) Run(run func(ctx context.Context, e *models.Event)) *MockIService_CreateEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Event))
	})
	return _c
}

func (_c *MockIService_CreateEvent_Call) Return(_a0 int, _a1 error) *MockIService_CreateEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_CreateEvent_Call) RunAndReturn(run func(context.Context, *models.Event) (int, error)) *MockIService_CreateEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInstitution provides a mock function with given fields: ctx, i
func (_m *MockIService) CreateInstitution(ctx context.Context, i *models.Institution) (int, error) {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for CreateInstitution")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Institution) (int, error)); ok {
		return rf(ctx, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Institution) int); ok {
		r0 = rf(ctx, i)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Institution) error); ok {
		r1 = rf(ctx, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_CreateInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInstitution'
type MockIService_CreateInstitution_Call struct {
	*mock.Call
}

// CreateInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - i *models.Institution
func (_e *MockIService_Expecter) CreateInstitution(ctx interface{}, i interface{}) *MockIService_CreateInstitution_Call {
	return &MockIService_CreateInstitution_Call{Call: _e.mock.On("CreateInstitution", ctx, i)}
}

func (_c *MockIService_CreateInstitution_Call) Run(run func(ctx context.Context, i *models.Institution)) *MockIService_CreateInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Institution))
	})
	return _c
}

func (_c *MockIService_CreateInstitution_Call) Return(_a0 int, _a1 error) *MockIService_CreateInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_CreateInstitution_Call) RunAndReturn(run func(context.Context, *models.Institution) (int, error)) *MockIService_CreateInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNeed provides a mock function with given fields: ctx, need
func (_m *MockIService) CreateNeed(ctx context.Context, need *models.Need) (int, error) {
	ret := _m.Called(ctx, need)

	if len(ret) == 0 {
		panic("no return value specified for CreateNeed")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) (int, error)); ok {
		return rf(ctx, need)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) int); ok {
		r0 = rf(ctx, need)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Need) error); ok {
		r1 = rf(ctx, need)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_CreateNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNeed'
type MockIService_CreateNeed_Call struct {
	*mock.Call
}

// CreateNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - need *models.Need
func (_e *MockIService_Expecter) CreateNeed(ctx interface{}, need interface{}) *MockIService_CreateNeed_Call {
	return &MockIService_CreateNeed_Call{Call: _e.mock.On("CreateNeed", ctx, need)}
}

func (_c *MockIService_CreateNeed_Call) Run(run func(ctx context.Context, need *models.Need)) *MockIService_CreateNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Need))
	})
	return _c
}

func (_c *MockIService_CreateNeed_Call) Return(_a0 int, _a1 error) *MockIService_CreateNeed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_CreateNeed_Call) RunAndReturn(run func(context.Context, *models.Need) (int, error)) *MockIService_CreateNeed_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *MockIService) CreateUser(ctx context.Context, user *models.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockIService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockIService_Expecter) CreateUser(ctx interface{}, user interface{}) *MockIService_CreateUser_Call {
	return &MockIService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *MockIService_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *MockIService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *MockIService_CreateUser_Call) Return(_a0 error) *MockIService_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *MockIService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNeed provides a mock function with given fields: ctx, id
func (_m *MockIService) DeleteNeed(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_DeleteNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNeed'
type MockIService_DeleteNeed_Call struct {
	*mock.Call
}

// DeleteNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) DeleteNeed(ctx interface{}, id interface{}) *MockIService_DeleteNeed_Call {
	return &MockIService_DeleteNeed_Call{Call: _e.mock.On("DeleteNeed", ctx, id)}
}

func (_c *MockIService_DeleteNeed_Call) Run(run func(ctx context.Context, id int)) *MockIService_DeleteNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_DeleteNeed_Call) Return(_a0 error) *MockIService_DeleteNeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_DeleteNeed_Call) RunAndReturn(run func(context.Context, int) error) *MockIService_DeleteNeed_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCampaigns provides a mock function with given fields: ctx, q
func (_m *MockIService) GetAllCampaigns(ctx context.Context, q models.CampaignListQuery) (*models.CampaignPage, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCampaigns")
	}

	var r0 *models.CampaignPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CampaignListQuery) (*models.CampaignPage, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CampaignListQuery) *models.CampaignPage); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CampaignPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CampaignListQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetAllCampaigns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCampaigns'
type MockIService_GetAllCampaigns_Call struct {
	*mock.Call
}

// GetAllCampaigns is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.CampaignListQuery
func (_e *MockIService_Expecter) GetAllCampaigns(ctx interface{}, q interface{}) *MockIService_GetAllCampaigns_Call {
	return &MockIService_GetAllCampaigns_Call{Call: _e.mock.On("GetAllCampaigns", ctx, q)}
}

func (_c *MockIService_GetAllCampaigns_Call) Run(run func(ctx context.Context, q models.CampaignListQuery)) *MockIService_GetAllCampaigns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CampaignListQuery))
	})
	return _c
}

func (_c *MockIService_GetAllCampaigns_Call) Return(_a0 *models.CampaignPage, _a1 error) *MockIService_GetAllCampaigns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetAllCampaigns_Call) RunAndReturn(run func(context.Context, models.CampaignListQuery) (*models.CampaignPage, error)) *MockIService_GetAllCampaigns_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllEvents provides a mock function with given fields: ctx, q
func (_m *MockIService) GetAllEvents(ctx context.Context, q models.EventListQuery) (*models.EventPage, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetAllEvents")
	}

	var r0 *models.EventPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.EventListQuery) (*models.EventPage, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.EventListQuery) *models.EventPage); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.EventListQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetAllEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEvents'
type MockIService_GetAllEvents_Call struct {
	*mock.Call
}

// GetAllEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.EventListQuery
func (_e *MockIService_Expecter) GetAllEvents(ctx interface{}, q interface{}) *MockIService_GetAllEvents_Call {
	return &MockIService_GetAllEvents_Call{Call: _e.mock.On("GetAllEvents", ctx, q)}
}

func (_c *MockIService_GetAllEvents_Call) Run(run func(ctx context.Context, q models.EventListQuery)) *MockIService_GetAllEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.EventListQuery))
	})
	return _c
}

func (_c *MockIService_GetAllEvents_Call) Return(_a0 *models.EventPage, _a1 error) *MockIService_GetAllEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetAllEvents_Call) RunAndReturn(run func(context.Context, models.EventListQuery) (*models.EventPage, error)) *MockIService_GetAllEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllInstitutions provides a mock function with given fields: ctx, q
func (_m *MockIService) GetAllInstitutions(ctx context.Context, q models.InstitutionListQuery) (*models.InstitutionPage, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetAllInstitutions")
	}

	var r0 *models.InstitutionPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.InstitutionListQuery) (*models.InstitutionPage, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.InstitutionListQuery) *models.InstitutionPage); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.InstitutionPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.InstitutionListQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetAllInstitutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllInstitutions'
type MockIService_GetAllInstitutions_Call struct {
	*mock.Call
}

// GetAllInstitutions is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.InstitutionListQuery
func (_e *MockIService_Expecter) GetAllInstitutions(ctx interface{}, q interface{}) *MockIService_GetAllInstitutions_Call {
	return &MockIService_GetAllInstitutions_Call{Call: _e.mock.On("GetAllInstitutions", ctx, q)}
}

func (_c *MockIService_GetAllInstitutions_Call) Run(run func(ctx context.Context, q models.InstitutionListQuery)) *MockIService_GetAllInstitutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.InstitutionListQuery))
	})
	return _c
}

func (_c *MockIService_GetAllInstitutions_Call) Return(_a0 *models.InstitutionPage, _a1 error) *MockIService_GetAllInstitutions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetAllInstitutions_Call) RunAndReturn(run func(context.Context, models.InstitutionListQuery) (*models.InstitutionPage, error)) *MockIService_GetAllInstitutions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTeamMembers provides a mock function with given fields: ctx
func (_m *MockIService) GetAllTeamMembers(ctx context.Context) ([]*models.TeamMember, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTeamMembers")
	}

	var r0 []*models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.TeamMember, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.TeamMember); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetAllTeamMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTeamMembers'
type MockIService_GetAllTeamMembers_Call struct {
	*mock.Call
}

// GetAllTeamMembers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) GetAllTeamMembers(ctx interface{}) *MockIService_GetAllTeamMembers_Call {
	return &MockIService_GetAllTeamMembers_Call{Call: _e.mock.On("GetAllTeamMembers", ctx)}
}

func (_c *MockIService_GetAllTeamMembers_Call) Run(run func(ctx context.Context)) *MockIService_GetAllTeamMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIService_GetAllTeamMembers_Call) Return(_a0 []*models.TeamMember, _a1 error) *MockIService_GetAllTeamMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetAllTeamMembers_Call) RunAndReturn(run func(context.Context) ([]*models.TeamMember, error)) *MockIService_GetAllTeamMembers_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllVacancies provides a mock function with given fields: ctx
func (_m *MockIService) GetAllVacancies(ctx context.Context) ([]*models.Vacancy, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllVacancies")
	}

	var r0 []*models.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Vacancy, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Vacancy); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetAllVacancies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllVacancies'
type MockIService_GetAllVacancies_Call struct {
	*mock.Call
}

// GetAllVacancies is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) GetAllVacancies(ctx interface{}) *MockIService_GetAllVacancies_Call {
	return &MockIService_GetAllVacancies_Call{Call: _e.mock.On("GetAllVacancies", ctx)}
}

func (_c *MockIService_GetAllVacancies_Call) Run(run func(ctx context.Context)) *MockIService_GetAllVacancies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIService_GetAllVacancies_Call) Return(_a0 []*models.Vacancy, _a1 error) *MockIService_GetAllVacancies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetAllVacancies_Call) RunAndReturn(run func(context.Context) ([]*models.Vacancy, error)) *MockIService_GetAllVacancies_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByInstitution provides a mock function with given fields: ctx, institutionID
func (_m *MockIService) GetBookingsByInstitution(ctx context.Context, institutionID int) ([]*models.Booking, error) {
	ret := _m.Called(ctx, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByInstitution")
	}

	var r0 []*models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.Booking, error)); ok {
		return rf(ctx, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Booking); ok {
		r0 = rf(ctx, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetBookingsByInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByInstitution'
type MockIService_GetBookingsByInstitution_Call struct {
	*mock.Call
}

// GetBookingsByInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - institutionID int
func (_e *MockIService_Expecter) GetBookingsByInstitution(ctx interface{}, institutionID interface{}) *MockIService_GetBookingsByInstitution_Call {
	return &MockIService_GetBookingsByInstitution_Call{Call: _e.mock.On("GetBookingsByInstitution", ctx, institutionID)}
}

func (_c *MockIService_GetBookingsByInstitution_Call) Run(run func(ctx context.Context, institutionID int)) *MockIService_GetBookingsByInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetBookingsByInstitution_Call) Return(_a0 []*models.Booking, _a1 error) *MockIService_GetBookingsByInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetBookingsByInstitution_Call) RunAndReturn(run func(context.Context, int) ([]*models.Booking, error)) *MockIService_GetBookingsByInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookingsByUser provides a mock function with given fields: ctx, userID
func (_m *MockIService) GetBookingsByUser(ctx context.Context, userID int) ([]*models.Booking, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookingsByUser")
	}

	var r0 []*models.Booking
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.Booking, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.Booking); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Booking)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetBookingsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookingsByUser'
type MockIService_GetBookingsByUser_Call struct {
	*mock.Call
}

// GetBookingsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockIService_Expecter) GetBookingsByUser(ctx interface{}, userID interface{}) *MockIService_GetBookingsByUser_Call {
	return &MockIService_GetBookingsByUser_Call{Call: _e.mock.On("GetBookingsByUser", ctx, userID)}
}

func (_c *MockIService_GetBookingsByUser_Call) Run(run func(ctx context.Context, userID int)) *MockIService_GetBookingsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetBookingsByUser_Call) Return(_a0 []*models.Booking, _a1 error) *MockIService_GetBookingsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetBookingsByUser_Call) RunAndReturn(run func(context.Context, int) ([]*models.Booking, error)) *MockIService_GetBookingsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetCampaignByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetCampaignByID(ctx context.Context, id int) (*models.PublicCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignByID")
	}

	var r0 *models.PublicCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.PublicCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.PublicCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PublicCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetCampaignByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaignByID'
type MockIService_GetCampaignByID_Call struct {
	*mock.Call
}

// GetCampaignByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetCampaignByID(ctx interface{}, id interface{}) *MockIService_GetCampaignByID_Call {
	return &MockIService_GetCampaignByID_Call{Call: _e.mock.On("GetCampaignByID", ctx, id)}
}

func (_c *MockIService_GetCampaignByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetCampaignByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetCampaignByID_Call) Return(_a0 *models.PublicCampaign, _a1 error) *MockIService_GetCampaignByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetCampaignByID_Call) RunAndReturn(run func(context.Context, int) (*models.PublicCampaign, error)) *MockIService_GetCampaignByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDonationsByCampaign provides a mock function with given fields: ctx, campaignID
func (_m *MockIService) GetDonationsByCampaign(ctx context.Context, campaignID int) (*models.LedgerEntryPage, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetDonationsByCampaign")
	}

	var r0 *models.LedgerEntryPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.LedgerEntryPage, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.LedgerEntryPage); ok {
		r0 = rf(ctx, campaignID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LedgerEntryPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetDonationsByCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDonationsByCampaign'
type MockIService_GetDonationsByCampaign_Call struct {
	*mock.Call
}

// GetDonationsByCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID int
func (_e *MockIService_Expecter) GetDonationsByCampaign(ctx interface{}, campaignID interface{}) *MockIService_GetDonationsByCampaign_Call {
	return &MockIService_GetDonationsByCampaign_Call{Call: _e.mock.On("GetDonationsByCampaign", ctx, campaignID)}
}

func (_c *MockIService_GetDonationsByCampaign_Call) Run(run func(ctx context.Context, campaignID int)) *MockIService_GetDonationsByCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetDonationsByCampaign_Call) Return(_a0 *models.LedgerEntryPage, _a1 error) *MockIService_GetDonationsByCampaign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetDonationsByCampaign_Call) RunAndReturn(run func(context.Context, int) (*models.LedgerEntryPage, error)) *MockIService_GetDonationsByCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// GetDonationsByDonorUser provides a mock function with given fields: ctx, userID
func (_m *MockIService) GetDonationsByDonorUser(ctx context.Context, userID int) (*models.LedgerEntryPage, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDonationsByDonorUser")
	}

	var r0 *models.LedgerEntryPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.LedgerEntryPage, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.LedgerEntryPage); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LedgerEntryPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetDonationsByDonorUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDonationsByDonorUser'
type MockIService_GetDonationsByDonorUser_Call struct {
	*mock.Call
}

// GetDonationsByDonorUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockIService_Expecter) GetDonationsByDonorUser(ctx interface{}, userID interface{}) *MockIService_GetDonationsByDonorUser_Call {
	return &MockIService_GetDonationsByDonorUser_Call{Call: _e.mock.On("GetDonationsByDonorUser", ctx, userID)}
}

func (_c *MockIService_GetDonationsByDonorUser_Call) Run(run func(ctx context.Context, userID int)) *MockIService_GetDonationsByDonorUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetDonationsByDonorUser_Call) Return(_a0 *models.LedgerEntryPage, _a1 error) *MockIService_GetDonationsByDonorUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetDonationsByDonorUser_Call) RunAndReturn(run func(context.Context, int) (*models.LedgerEntryPage, error)) *MockIService_GetDonationsByDonorUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetEventByID(ctx context.Context, id int) (*models.Event, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEventByID")
	}

	var r0 *models.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetEventByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventByID'
type MockIService_GetEventByID_Call struct {
	*mock.Call
}

// GetEventByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetEventByID(ctx interface{}, id interface{}) *MockIService_GetEventByID_Call {
	return &MockIService_GetEventByID_Call{Call: _e.mock.On("GetEventByID", ctx, id)}
}

func (_c *MockIService_GetEventByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetEventByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetEventByID_Call) Return(_a0 *models.Event, _a1 error) *MockIService_GetEventByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetEventByID_Call) RunAndReturn(run func(context.Context, int) (*models.Event, error)) *MockIService_GetEventByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventDetail provides a mock function with given fields: ctx, q
func (_m *MockIService) GetEventDetail(ctx context.Context, q models.EventDetailQuery) (*models.EventResponse, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetEventDetail")
	}

	var r0 *models.EventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.EventDetailQuery) (*models.EventResponse, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.EventDetailQuery) *models.EventResponse); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.EventDetailQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetEventDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventDetail'
type MockIService_GetEventDetail_Call struct {
	*mock.Call
}

// GetEventDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.EventDetailQuery
func (_e *MockIService_Expecter) GetEventDetail(ctx interface{}, q interface{}) *MockIService_GetEventDetail_Call {
	return &MockIService_GetEventDetail_Call{Call: _e.mock.On("GetEventDetail", ctx, q)}
}

func (_c *MockIService_GetEventDetail_Call) Run(run func(ctx context.Context, q models.EventDetailQuery)) *MockIService_GetEventDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.EventDetailQuery))
	})
	return _c
}

func (_c *MockIService_GetEventDetail_Call) Return(_a0 *models.EventResponse, _a1 error) *MockIService_GetEventDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetEventDetail_Call) RunAndReturn(run func(context.Context, models.EventDetailQuery) (*models.EventResponse, error)) *MockIService_GetEventDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstitutionByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetInstitutionByID(ctx context.Context, id int) (*models.Institution, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetInstitutionByID")
	}

	var r0 *models.Institution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Institution, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Institution); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Institution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetInstitutionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstitutionByID'
type MockIService_GetInstitutionByID_Call struct {
	*mock.Call
}

// GetInstitutionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetInstitutionByID(ctx interface{}, id interface{}) *MockIService_GetInstitutionByID_Call {
	return &MockIService_GetInstitutionByID_Call{Call: _e.mock.On("GetInstitutionByID", ctx, id)}
}

func (_c *MockIService_GetInstitutionByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetInstitutionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetInstitutionByID_Call) Return(_a0 *models.Institution, _a1 error) *MockIService_GetInstitutionByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetInstitutionByID_Call) RunAndReturn(run func(context.Context, int) (*models.Institution, error)) *MockIService_GetInstitutionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstitutionEvents provides a mock function with given fields: ctx, institutionID
func (_m *MockIService) GetInstitutionEvents(ctx context.Context, institutionID int) ([]*models.EventResponse, error) {
	ret := _m.Called(ctx, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for GetInstitutionEvents")
	}

	var r0 []*models.EventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.EventResponse, error)); ok {
		return rf(ctx, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.EventResponse); ok {
		r0 = rf(ctx, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.EventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetInstitutionEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstitutionEvents'
type MockIService_GetInstitutionEvents_Call struct {
	*mock.Call
}

// GetInstitutionEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - institutionID int
func (_e *MockIService_Expecter) GetInstitutionEvents(ctx interface{}, institutionID interface{}) *MockIService_GetInstitutionEvents_Call {
	return &MockIService_GetInstitutionEvents_Call{Call: _e.mock.On("GetInstitutionEvents", ctx, institutionID)}
}

func (_c *MockIService_GetInstitutionEvents_Call) Run(run func(ctx context.Context, institutionID int)) *MockIService_GetInstitutionEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetInstitutionEvents_Call) Return(_a0 []*models.EventResponse, _a1 error) *MockIService_GetInstitutionEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetInstitutionEvents_Call) RunAndReturn(run func(context.Context, int) ([]*models.EventResponse, error)) *MockIService_GetInstitutionEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetNeedByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetNeedByID(ctx context.Context, id int) (*models.Need, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNeedByID")
	}

	var r0 *models.Need
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Need, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Need); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Need)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetNeedByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNeedByID'
type MockIService_GetNeedByID_Call struct {
	*mock.Call
}

// GetNeedByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetNeedByID(ctx interface{}, id interface{}) *MockIService_GetNeedByID_Call {
	return &MockIService_GetNeedByID_Call{Call: _e.mock.On("GetNeedByID", ctx, id)}
}

func (_c *MockIService_GetNeedByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetNeedByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetNeedByID_Call) Return(_a0 *models.Need, _a1 error) *MockIService_GetNeedByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetNeedByID_Call) RunAndReturn(run func(context.Context, int) (*models.Need, error)) *MockIService_GetNeedByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNeedsByInstitution provides a mock function with given fields: ctx, filter, institutionID
func (_m *MockIService) GetNeedsByInstitution(ctx context.Context, filter filters.NeedsFilter, institutionID int) ([]*models.Need, error) {
	ret := _m.Called(ctx, filter, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for GetNeedsByInstitution")
	}

	var r0 []*models.Need
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, filters.NeedsFilter, int) ([]*models.Need, error)); ok {
		return rf(ctx, filter, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, filters.NeedsFilter, int) []*models.Need); ok {
		r0 = rf(ctx, filter, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Need)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, filters.NeedsFilter, int) error); ok {
		r1 = rf(ctx, filter, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetNeedsByInstitution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNeedsByInstitution'
type MockIService_GetNeedsByInstitution_Call struct {
	*mock.Call
}

// GetNeedsByInstitution is a helper method to define mock.On call
//   - ctx context.Context
//   - filter filters.NeedsFilter
//   - institutionID int
func (_e *MockIService_Expecter) GetNeedsByInstitution(ctx interface{}, filter interface{}, institutionID interface{}) *MockIService_GetNeedsByInstitution_Call {
	return &MockIService_GetNeedsByInstitution_Call{Call: _e.mock.On("GetNeedsByInstitution", ctx, filter, institutionID)}
}

func (_c *MockIService_GetNeedsByInstitution_Call) Run(run func(ctx context.Context, filter filters.NeedsFilter, institutionID int)) *MockIService_GetNeedsByInstitution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(filters.NeedsFilter), args[2].(int))
	})
	return _c
}

func (_c *MockIService_GetNeedsByInstitution_Call) Return(_a0 []*models.Need, _a1 error) *MockIService_GetNeedsByInstitution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetNeedsByInstitution_Call) RunAndReturn(run func(context.Context, filters.NeedsFilter, int) ([]*models.Need, error)) *MockIService_GetNeedsByInstitution_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicStats provides a mock function with given fields: ctx
func (_m *MockIService) GetPublicStats(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicStats")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetPublicStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicStats'
type MockIService_GetPublicStats_Call struct {
	*mock.Call
}

// GetPublicStats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIService_Expecter) GetPublicStats(ctx interface{}) *MockIService_GetPublicStats_Call {
	return &MockIService_GetPublicStats_Call{Call: _e.mock.On("GetPublicStats", ctx)}
}

func (_c *MockIService_GetPublicStats_Call) Run(run func(ctx context.Context)) *MockIService_GetPublicStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIService_GetPublicStats_Call) Return(_a0 map[string]int, _a1 error) *MockIService_GetPublicStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetPublicStats_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *MockIService_GetPublicStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetTeamMemberByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetTeamMemberByID(ctx context.Context, id int) (*models.TeamMember, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTeamMemberByID")
	}

	var r0 *models.TeamMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.TeamMember, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.TeamMember); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TeamMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetTeamMemberByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTeamMemberByID'
type MockIService_GetTeamMemberByID_Call struct {
	*mock.Call
}

// GetTeamMemberByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetTeamMemberByID(ctx interface{}, id interface{}) *MockIService_GetTeamMemberByID_Call {
	return &MockIService_GetTeamMemberByID_Call{Call: _e.mock.On("GetTeamMemberByID", ctx, id)}
}

func (_c *MockIService_GetTeamMemberByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetTeamMemberByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetTeamMemberByID_Call) Return(_a0 *models.TeamMember, _a1 error) *MockIService_GetTeamMemberByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetTeamMemberByID_Call) RunAndReturn(run func(context.Context, int) (*models.TeamMember, error)) *MockIService_GetTeamMemberByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockIService) GetUserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockIService_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockIService_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockIService_GetUserByEmail_Call {
	return &MockIService_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockIService_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockIService_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIService_GetUserByEmail_Call) Return(_a0 *models.User, _a1 error) *MockIService_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *MockIService_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetUserByID(ctx context.Context, id int) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockIService_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockIService_GetUserByID_Call {
	return &MockIService_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockIService_GetUserByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetUserByID_Call) Return(_a0 *models.User, _a1 error) *MockIService_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetUserByID_Call) RunAndReturn(run func(context.Context, int) (*models.User, error)) *MockIService_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVacancyByID provides a mock function with given fields: ctx, id
func (_m *MockIService) GetVacancyByID(ctx context.Context, id int) (*models.Vacancy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetVacancyByID")
	}

	var r0 *models.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Vacancy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Vacancy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_GetVacancyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVacancyByID'
type MockIService_GetVacancyByID_Call struct {
	*mock.Call
}

// GetVacancyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockIService_Expecter) GetVacancyByID(ctx interface{}, id interface{}) *MockIService_GetVacancyByID_Call {
	return &MockIService_GetVacancyByID_Call{Call: _e.mock.On("GetVacancyByID", ctx, id)}
}

func (_c *MockIService_GetVacancyByID_Call) Run(run func(ctx context.Context, id int)) *MockIService_GetVacancyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_GetVacancyByID_Call) Return(_a0 *models.Vacancy, _a1 error) *MockIService_GetVacancyByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_GetVacancyByID_Call) RunAndReturn(run func(context.Context, int) (*models.Vacancy, error)) *MockIService_GetVacancyByID_Call {
	_c.Call.Return(run)
	return _c
}

// JoinEvent provides a mock function with given fields: ctx, eventID, userID
func (_m *MockIService) JoinEvent(ctx context.Context, eventID int, userID int) error {
	ret := _m.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_JoinEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinEvent'
type MockIService_JoinEvent_Call struct {
	*mock.Call
}

// JoinEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int
//   - userID int
func (_e *MockIService_Expecter) JoinEvent(ctx interface{}, eventID interface{}, userID interface{}) *MockIService_JoinEvent_Call {
	return &MockIService_JoinEvent_Call{Call: _e.mock.On("JoinEvent", ctx, eventID, userID)}
}

func (_c *MockIService_JoinEvent_Call) Run(run func(ctx context.Context, eventID int, userID int)) *MockIService_JoinEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_JoinEvent_Call) Return(_a0 error) *MockIService_JoinEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_JoinEvent_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_JoinEvent_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveEvent provides a mock function with given fields: ctx, eventID, userID
func (_m *MockIService) LeaveEvent(ctx context.Context, eventID int, userID int) error {
	ret := _m.Called(ctx, eventID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, eventID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_LeaveEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveEvent'
type MockIService_LeaveEvent_Call struct {
	*mock.Call
}

// LeaveEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int
//   - userID int
func (_e *MockIService_Expecter) LeaveEvent(ctx interface{}, eventID interface{}, userID interface{}) *MockIService_LeaveEvent_Call {
	return &MockIService_LeaveEvent_Call{Call: _e.mock.On("LeaveEvent", ctx, eventID, userID)}
}

func (_c *MockIService_LeaveEvent_Call) Run(run func(ctx context.Context, eventID int, userID int)) *MockIService_LeaveEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_LeaveEvent_Call) Return(_a0 error) *MockIService_LeaveEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_LeaveEvent_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_LeaveEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, phone, password
func (_m *MockIService) Login(ctx context.Context, phone string, password string) (*models.TokenResponse, error) {
	ret := _m.Called(ctx, phone, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.TokenResponse, error)); ok {
		return rf(ctx, phone, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.TokenResponse); ok {
		r0 = rf(ctx, phone, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, phone, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockIService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - password string
func (_e *MockIService_Expecter) Login(ctx interface{}, phone interface{}, password interface{}) *MockIService_Login_Call {
	return &MockIService_Login_Call{Call: _e.mock.On("Login", ctx, phone, password)}
}

func (_c *MockIService_Login_Call) Run(run func(ctx context.Context, phone string, password string)) *MockIService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIService_Login_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockIService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_Login_Call) RunAndReturn(run func(context.Context, string, string) (*models.TokenResponse, error)) *MockIService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// LoginOAuth provides a mock function with given fields: ctx, oauthUserInfo
func (_m *MockIService) LoginOAuth(ctx context.Context, oauthUserInfo models.OAuthUserInfo) (*models.TokenResponse, error) {
	ret := _m.Called(ctx, oauthUserInfo)

	if len(ret) == 0 {
		panic("no return value specified for LoginOAuth")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OAuthUserInfo) (*models.TokenResponse, error)); ok {
		return rf(ctx, oauthUserInfo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OAuthUserInfo) *models.TokenResponse); ok {
		r0 = rf(ctx, oauthUserInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OAuthUserInfo) error); ok {
		r1 = rf(ctx, oauthUserInfo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_LoginOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginOAuth'
type MockIService_LoginOAuth_Call struct {
	*mock.Call
}

// LoginOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - oauthUserInfo models.OAuthUserInfo
func (_e *MockIService_Expecter) LoginOAuth(ctx interface{}, oauthUserInfo interface{}) *MockIService_LoginOAuth_Call {
	return &MockIService_LoginOAuth_Call{Call: _e.mock.On("LoginOAuth", ctx, oauthUserInfo)}
}

func (_c *MockIService_LoginOAuth_Call) Run(run func(ctx context.Context, oauthUserInfo models.OAuthUserInfo)) *MockIService_LoginOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OAuthUserInfo))
	})
	return _c
}

func (_c *MockIService_LoginOAuth_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockIService_LoginOAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_LoginOAuth_Call) RunAndReturn(run func(context.Context, models.OAuthUserInfo) (*models.TokenResponse, error)) *MockIService_LoginOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessDonation provides a mock function with given fields: ctx, donation
func (_m *MockIService) ProcessDonation(ctx context.Context, donation models.DonationRequest) (*models.LedgerEntry, error) {
	ret := _m.Called(ctx, donation)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDonation")
	}

	var r0 *models.LedgerEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.DonationRequest) (*models.LedgerEntry, error)); ok {
		return rf(ctx, donation)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.DonationRequest) *models.LedgerEntry); ok {
		r0 = rf(ctx, donation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LedgerEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.DonationRequest) error); ok {
		r1 = rf(ctx, donation)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_ProcessDonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDonation'
type MockIService_ProcessDonation_Call struct {
	*mock.Call
}

// ProcessDonation is a helper method to define mock.On call
//   - ctx context.Context
//   - donation models.DonationRequest
func (_e *MockIService_Expecter) ProcessDonation(ctx interface{}, donation interface{}) *MockIService_ProcessDonation_Call {
	return &MockIService_ProcessDonation_Call{Call: _e.mock.On("ProcessDonation", ctx, donation)}
}

func (_c *MockIService_ProcessDonation_Call) Run(run func(ctx context.Context, donation models.DonationRequest)) *MockIService_ProcessDonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.DonationRequest))
	})
	return _c
}

func (_c *MockIService_ProcessDonation_Call) Return(_a0 *models.LedgerEntry, _a1 error) *MockIService_ProcessDonation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_ProcessDonation_Call) RunAndReturn(run func(context.Context, models.DonationRequest) (*models.LedgerEntry, error)) *MockIService_ProcessDonation_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: ctx, refreshToken
func (_m *MockIService) RefreshTokens(ctx context.Context, refreshToken string) (*models.TokenResponse, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.TokenResponse, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.TokenResponse); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockIService_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockIService_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *MockIService_RefreshTokens_Call {
	return &MockIService_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *MockIService_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *MockIService_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIService_RefreshTokens_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockIService_RefreshTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_RefreshTokens_Call) RunAndReturn(run func(context.Context, string) (*models.TokenResponse, error)) *MockIService_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, email, phone, password, fullName, role, institutionID
func (_m *MockIService) Register(ctx context.Context, email string, phone string, password string, fullName string, role string, institutionID *int) (*models.TokenResponse, error) {
	ret := _m.Called(ctx, email, phone, password, fullName, role, institutionID)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *models.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, *int) (*models.TokenResponse, error)); ok {
		return rf(ctx, email, phone, password, fullName, role, institutionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, *int) *models.TokenResponse); ok {
		r0 = rf(ctx, email, phone, password, fullName, role, institutionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, *int) error); ok {
		r1 = rf(ctx, email, phone, password, fullName, role, institutionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockIService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - phone string
//   - password string
//   - fullName string
//   - role string
//   - institutionID *int
func (_e *MockIService_Expecter) Register(ctx interface{}, email interface{}, phone interface{}, password interface{}, fullName interface{}, role interface{}, institutionID interface{}) *MockIService_Register_Call {
	return &MockIService_Register_Call{Call: _e.mock.On("Register", ctx, email, phone, password, fullName, role, institutionID)}
}

func (_c *MockIService_Register_Call) Run(run func(ctx context.Context, email string, phone string, password string, fullName string, role string, institutionID *int)) *MockIService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(*int))
	})
	return _c
}

func (_c *MockIService_Register_Call) Return(_a0 *models.TokenResponse, _a1 error) *MockIService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_Register_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, *int) (*models.TokenResponse, error)) *MockIService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RejectBooking provides a mock function with given fields: ctx, bookingID, institutionUserID
func (_m *MockIService) RejectBooking(ctx context.Context, bookingID int, institutionUserID int) error {
	ret := _m.Called(ctx, bookingID, institutionUserID)

	if len(ret) == 0 {
		panic("no return value specified for RejectBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, bookingID, institutionUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_RejectBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectBooking'
type MockIService_RejectBooking_Call struct {
	*mock.Call
}

// RejectBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - institutionUserID int
func (_e *MockIService_Expecter) RejectBooking(ctx interface{}, bookingID interface{}, institutionUserID interface{}) *MockIService_RejectBooking_Call {
	return &MockIService_RejectBooking_Call{Call: _e.mock.On("RejectBooking", ctx, bookingID, institutionUserID)}
}

func (_c *MockIService_RejectBooking_Call) Run(run func(ctx context.Context, bookingID int, institutionUserID int)) *MockIService_RejectBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockIService_RejectBooking_Call) Return(_a0 error) *MockIService_RejectBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_RejectBooking_Call) RunAndReturn(run func(context.Context, int, int) error) *MockIService_RejectBooking_Call {
	_c.Call.Return(run)
	return _c
}

// RejectEvent provides a mock function with given fields: ctx, eventID
func (_m *MockIService) RejectEvent(ctx context.Context, eventID int) error {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for RejectEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, eventID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_RejectEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectEvent'
type MockIService_RejectEvent_Call struct {
	*mock.Call
}

// RejectEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID int
func (_e *MockIService_Expecter) RejectEvent(ctx interface{}, eventID interface{}) *MockIService_RejectEvent_Call {
	return &MockIService_RejectEvent_Call{Call: _e.mock.On("RejectEvent", ctx, eventID)}
}

func (_c *MockIService_RejectEvent_Call) Run(run func(ctx context.Context, eventID int)) *MockIService_RejectEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_RejectEvent_Call) Return(_a0 error) *MockIService_RejectEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_RejectEvent_Call) RunAndReturn(run func(context.Context, int) error) *MockIService_RejectEvent_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserRefreshTokens provides a mock function with given fields: ctx, userID
func (_m *MockIService) RevokeAllUserRefreshTokens(ctx context.Context, userID int) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_RevokeAllUserRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserRefreshTokens'
type MockIService_RevokeAllUserRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllUserRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *MockIService_Expecter) RevokeAllUserRefreshTokens(ctx interface{}, userID interface{}) *MockIService_RevokeAllUserRefreshTokens_Call {
	return &MockIService_RevokeAllUserRefreshTokens_Call{Call: _e.mock.On("RevokeAllUserRefreshTokens", ctx, userID)}
}

func (_c *MockIService_RevokeAllUserRefreshTokens_Call) Run(run func(ctx context.Context, userID int)) *MockIService_RevokeAllUserRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockIService_RevokeAllUserRefreshTokens_Call) Return(_a0 error) *MockIService_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_RevokeAllUserRefreshTokens_Call) RunAndReturn(run func(context.Context, int) error) *MockIService_RevokeAllUserRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// SendOTP provides a mock function with given fields: ctx, receiver
func (_m *MockIService) SendOTP(ctx context.Context, receiver string) (int, error) {
	ret := _m.Called(ctx, receiver)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, receiver)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, receiver)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, receiver)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockIService_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver string
func (_e *MockIService_Expecter) SendOTP(ctx interface{}, receiver interface{}) *MockIService_SendOTP_Call {
	return &MockIService_SendOTP_Call{Call: _e.mock.On("SendOTP", ctx, receiver)}
}

func (_c *MockIService_SendOTP_Call) Run(run func(ctx context.Context, receiver string)) *MockIService_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIService_SendOTP_Call) Return(_a0 int, _a1 error) *MockIService_SendOTP_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_SendOTP_Call) RunAndReturn(run func(context.Context, string) (int, error)) *MockIService_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMyBooking provides a mock function with given fields: ctx, bookingID, userID, qty
func (_m *MockIService) UpdateMyBooking(ctx context.Context, bookingID int, userID int, qty float64) error {
	ret := _m.Called(ctx, bookingID, userID, qty)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMyBooking")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, float64) error); ok {
		r0 = rf(ctx, bookingID, userID, qty)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_UpdateMyBooking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMyBooking'
type MockIService_UpdateMyBooking_Call struct {
	*mock.Call
}

// UpdateMyBooking is a helper method to define mock.On call
//   - ctx context.Context
//   - bookingID int
//   - userID int
//   - qty float64
func (_e *MockIService_Expecter) UpdateMyBooking(ctx interface{}, bookingID interface{}, userID interface{}, qty interface{}) *MockIService_UpdateMyBooking_Call {
	return &MockIService_UpdateMyBooking_Call{Call: _e.mock.On("UpdateMyBooking", ctx, bookingID, userID, qty)}
}

func (_c *MockIService_UpdateMyBooking_Call) Run(run func(ctx context.Context, bookingID int, userID int, qty float64)) *MockIService_UpdateMyBooking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(float64))
	})
	return _c
}

func (_c *MockIService_UpdateMyBooking_Call) Return(_a0 error) *MockIService_UpdateMyBooking_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_UpdateMyBooking_Call) RunAndReturn(run func(context.Context, int, int, float64) error) *MockIService_UpdateMyBooking_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNeed provides a mock function with given fields: ctx, n
func (_m *MockIService) UpdateNeed(ctx context.Context, n *models.Need) error {
	ret := _m.Called(ctx, n)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNeed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Need) error); ok {
		r0 = rf(ctx, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_UpdateNeed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNeed'
type MockIService_UpdateNeed_Call struct {
	*mock.Call
}

// UpdateNeed is a helper method to define mock.On call
//   - ctx context.Context
//   - n *models.Need
func (_e *MockIService_Expecter) UpdateNeed(ctx interface{}, n interface{}) *MockIService_UpdateNeed_Call {
	return &MockIService_UpdateNeed_Call{Call: _e.mock.On("UpdateNeed", ctx, n)}
}

func (_c *MockIService_UpdateNeed_Call) Run(run func(ctx context.Context, n *models.Need)) *MockIService_UpdateNeed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Need))
	})
	return _c
}

func (_c *MockIService_UpdateNeed_Call) Return(_a0 error) *MockIService_UpdateNeed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_UpdateNeed_Call) RunAndReturn(run func(context.Context, *models.Need) error) *MockIService_UpdateNeed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: ctx, userID, req
func (_m *MockIService) UpdateProfile(ctx context.Context, userID int, req models.UpdateProfileRequest) error {
	ret := _m.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, models.UpdateProfileRequest) error); ok {
		r0 = rf(ctx, userID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockIService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
//   - req models.UpdateProfileRequest
func (_e *MockIService_Expecter) UpdateProfile(ctx interface{}, userID interface{}, req interface{}) *MockIService_UpdateProfile_Call {
	return &MockIService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, userID, req)}
}

func (_c *MockIService_UpdateProfile_Call) Run(run func(ctx context.Context, userID int, req models.UpdateProfileRequest)) *MockIService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(models.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockIService_UpdateProfile_Call) Return(_a0 error) *MockIService_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIService_UpdateProfile_Call) RunAndReturn(run func(context.Context, int, models.UpdateProfileRequest) error) *MockIService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserOAuthInfoByEmail provides a mock function with given fields: ctx, info
func (_m *MockIService) UpdateUserOAuthInfoByEmail(ctx context.Context, info models.OAuthUserInfo) (*models.User, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserOAuthInfoByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.OAuthUserInfo) (*models.User, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.OAuthUserInfo) *models.User); ok {
		r0 = rf(ctx, info)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.OAuthUserInfo) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIService_UpdateUserOAuthInfoByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserOAuthInfoByEmail'
type MockIService_UpdateUserOAuthInfoByEmail_Call struct {
	*mock.Call
}

// UpdateUserOAuthInfoByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - info models.OAuthUserInfo
func (_e *MockIService_Expecter) UpdateUserOAuthInfoByEmail(ctx interface{}, info interface{}) *MockIService_UpdateUserOAuthInfoByEmail_Call {
	return &MockIService_UpdateUserOAuthInfoByEmail_Call{Call: _e.mock.On("UpdateUserOAuthInfoByEmail", ctx, info)}
}

func (_c *MockIService_UpdateUserOAuthInfoByEmail_Call) Run(run func(ctx context.Context, info models.OAuthUserInfo)) *MockIService_UpdateUserOAuthInfoByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.OAuthUserInfo))
	})
	return _c
}

func (_c *MockIService_UpdateUserOAuthInfoByEmail_Call) Return(_a0 *models.User, _a1 error) *MockIService_UpdateUserOAuthInfoByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIService_UpdateUserOAuthInfoByEmail_Call) RunAndReturn(run func(context.Context, models.OAuthUserInfo) (*models.User, error)) *MockIService_UpdateUserOAuthInfoByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserExists provides a mock function with given fields: ctx, email, phone
func (_m *MockIService) UserExists(ctx context.Context, email string, phone string) (bool, bool, bool, error) {
	ret := _m.Called(ctx, email, phone)

	if len(ret) == 0 {
		panic("no return value specified for UserExists")
	}

	var r0 bool
	var r1 bool
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, bool, bool, error)); ok {
		return rf(ctx, email, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, email, phone)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, email, phone)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) bool); ok {
		r2 = rf(ctx, email, phone)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string) error); ok {
		r3 = rf(ctx, email, phone)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockIService_UserExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserExists'
type MockIService_UserExists_Call struct {
	*mock.Call
}

// UserExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - phone string
func (_e *MockIService_Expecter) UserExists(ctx interface{}, email interface{}, phone interface{}) *MockIService_UserExists_Call {
	return &MockIService_UserExists_Call{Call: _e.mock.On("UserExists", ctx, email, phone)}
}

func (_c *MockIService_UserExists_Call) Run(run func(ctx context.Context, email string, phone string)) *MockIService_UserExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockIService_UserExists_Call) Return(_a0 bool, _a1 bool, _a2 bool, _a3 error) *MockIService_UserExists_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockIService_UserExists_Call) RunAndReturn(run func(context.Context, string, string) (bool, bool, bool, error)) *MockIService_UserExists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
