// Code generated by mockery v2.53.6. DO NOT EDIT.

package cache

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockICache is an autogenerated mock type for the ICache type
type MockICache struct {
	mock.Mock
}

type MockICache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICache) EXPECT() *MockICache_Expecter {
	return &MockICache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockICache) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockICache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockICache_Expecter) Delete(ctx interface{}, key interface{}) *MockICache_Delete_Call {
	return &MockICache_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockICache_Delete_Call) Run(run func(ctx context.Context, key string)) *MockICache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockICache_Delete_Call) Return(_a0 error) *MockICache_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICache_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockICache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockICache) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockICache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockICache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockICache_Expecter) Get(ctx interface{}, key interface{}) *MockICache_Get_Call {
	return &MockICache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockICache_Get_Call) Run(run func(ctx context.Context, key string)) *MockICache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockICache_Get_Call) Return(_a0 string, _a1 error) *MockICache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockICache_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockICache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function with given fields: ctx, key
func (_m *MockICache) Increment(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICache_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type MockICache_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockICache_Expecter) Increment(ctx interface{}, key interface{}) *MockICache_Increment_Call {
	return &MockICache_Increment_Call{Call: _e.mock.On("Increment", ctx, key)}
}

func (_c *MockICache_Increment_Call) Run(run func(ctx context.Context, key string)) *MockICache_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockICache_Increment_Call) Return(_a0 error) *MockICache_Increment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICache_Increment_Call) RunAndReturn(run func(context.Context, string) error) *MockICache_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockICache) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICache_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockICache_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockICache_Expecter) Ping(ctx interface{}) *MockICache_Ping_Call {
	return &MockICache_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockICache_Ping_Call) Run(run func(ctx context.Context)) *MockICache_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockICache_Ping_Call) Return(_a0 error) *MockICache_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICache_Ping_Call) RunAndReturn(run func(context.Context) error) *MockICache_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockICache) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockICache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *MockICache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockICache_Set_Call {
	return &MockICache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockICache_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *MockICache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockICache_Set_Call) Return(_a0 error) *MockICache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICache_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockICache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICache creates a new instance of MockICache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICache {
	mock := &MockICache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
