// Code generated by mockery v2.53.6. DO NOT EDIT.

package services

import (
	context "context"
	models "shb/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockLedgerRepository is an autogenerated mock type for the LedgerRepository type
type MockLedgerRepository struct {
	mock.Mock
}

type MockLedgerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerRepository) EXPECT() *MockLedgerRepository_Expecter {
	return &MockLedgerRepository_Expecter{mock: &_m.Mock}
}

// CreateLedgerEntry provides a mock function with given fields: ctx, l
func (_m *MockLedgerRepository) CreateLedgerEntry(ctx context.Context, l *models.LedgerEntry) error {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for CreateLedgerEntry")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LedgerEntry) error); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerRepository_CreateLedgerEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLedgerEntry'
type MockLedgerRepository_CreateLedgerEntry_Call struct {
	*mock.Call
}

// CreateLedgerEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - l *models.LedgerEntry
func (_e *MockLedgerRepository_Expecter) CreateLedgerEntry(ctx interface{}, l interface{}) *MockLedgerRepository_CreateLedgerEntry_Call {
	return &MockLedgerRepository_CreateLedgerEntry_Call{Call: _e.mock.On("CreateLedgerEntry", ctx, l)}
}

func (_c *MockLedgerRepository_CreateLedgerEntry_Call) Run(run func(ctx context.Context, l *models.LedgerEntry)) *MockLedgerRepository_CreateLedgerEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LedgerEntry))
	})
	return _c
}

func (_c *MockLedgerRepository_CreateLedgerEntry_Call) Return(_a0 error) *MockLedgerRepository_CreateLedgerEntry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerRepository_CreateLedgerEntry_Call) RunAndReturn(run func(context.Context, *models.LedgerEntry) error) *MockLedgerRepository_CreateLedgerEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLedgerEntries provides a mock function with given fields: ctx, q
func (_m *MockLedgerRepository) GetAllLedgerEntries(ctx context.Context, q models.LedgerEntryListQuery) (*models.LedgerEntryPage, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetAllLedgerEntries")
	}

	var r0 *models.LedgerEntryPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.LedgerEntryListQuery) (*models.LedgerEntryPage, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.LedgerEntryListQuery) *models.LedgerEntryPage); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LedgerEntryPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.LedgerEntryListQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerRepository_GetAllLedgerEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLedgerEntries'
type MockLedgerRepository_GetAllLedgerEntries_Call struct {
	*mock.Call
}

// GetAllLedgerEntries is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.LedgerEntryListQuery
func (_e *MockLedgerRepository_Expecter) GetAllLedgerEntries(ctx interface{}, q interface{}) *MockLedgerRepository_GetAllLedgerEntries_Call {
	return &MockLedgerRepository_GetAllLedgerEntries_Call{Call: _e.mock.On("GetAllLedgerEntries", ctx, q)}
}

func (_c *MockLedgerRepository_GetAllLedgerEntries_Call) Run(run func(ctx context.Context, q models.LedgerEntryListQuery)) *MockLedgerRepository_GetAllLedgerEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.LedgerEntryListQuery))
	})
	return _c
}

func (_c *MockLedgerRepository_GetAllLedgerEntries_Call) Return(_a0 *models.LedgerEntryPage, _a1 error) *MockLedgerRepository_GetAllLedgerEntries_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerRepository_GetAllLedgerEntries_Call) RunAndReturn(run func(context.Context, models.LedgerEntryListQuery) (*models.LedgerEntryPage, error)) *MockLedgerRepository_GetAllLedgerEntries_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalDonationsByCampaign provides a mock function with given fields: ctx, campaignID
func (_m *MockLedgerRepository) GetTotalDonationsByCampaign(ctx context.Context, campaignID int) (float64, error) {
	ret := _m.Called(ctx, campaignID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalDonationsByCampaign")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (float64, error)); ok {
		return rf(ctx, campaignID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) float64); ok {
		r0 = rf(ctx, campaignID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, campaignID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLedgerRepository_GetTotalDonationsByCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalDonationsByCampaign'
type MockLedgerRepository_GetTotalDonationsByCampaign_Call struct {
	*mock.Call
}

// GetTotalDonationsByCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - campaignID int
func (_e *MockLedgerRepository_Expecter) GetTotalDonationsByCampaign(ctx interface{}, campaignID interface{}) *MockLedgerRepository_GetTotalDonationsByCampaign_Call {
	return &MockLedgerRepository_GetTotalDonationsByCampaign_Call{Call: _e.mock.On("GetTotalDonationsByCampaign", ctx, campaignID)}
}

func (_c *MockLedgerRepository_GetTotalDonationsByCampaign_Call) Run(run func(ctx context.Context, campaignID int)) *MockLedgerRepository_GetTotalDonationsByCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockLedgerRepository_GetTotalDonationsByCampaign_Call) Return(_a0 float64, _a1 error) *MockLedgerRepository_GetTotalDonationsByCampaign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLedgerRepository_GetTotalDonationsByCampaign_Call) RunAndReturn(run func(context.Context, int) (float64, error)) *MockLedgerRepository_GetTotalDonationsByCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDonation provides a mock function with given fields: ctx, l
func (_m *MockLedgerRepository) RecordDonation(ctx context.Context, l *models.LedgerEntry) error {
	ret := _m.Called(ctx, l)

	if len(ret) == 0 {
		panic("no return value specified for RecordDonation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LedgerEntry) error); ok {
		r0 = rf(ctx, l)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLedgerRepository_RecordDonation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDonation'
type MockLedgerRepository_RecordDonation_Call struct {
	*mock.Call
}

// RecordDonation is a helper method to define mock.On call
//   - ctx context.Context
//   - l *models.LedgerEntry
func (_e *MockLedgerRepository_Expecter) RecordDonation(ctx interface{}, l interface{}) *MockLedgerRepository_RecordDonation_Call {
	return &MockLedgerRepository_RecordDonation_Call{Call: _e.mock.On("RecordDonation", ctx, l)}
}

func (_c *MockLedgerRepository_RecordDonation_Call) Run(run func(ctx context.Context, l *models.LedgerEntry)) *MockLedgerRepository_RecordDonation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LedgerEntry))
	})
	return _c
}

func (_c *MockLedgerRepository_RecordDonation_Call) Return(_a0 error) *MockLedgerRepository_RecordDonation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLedgerRepository_RecordDonation_Call) RunAndReturn(run func(context.Context, *models.LedgerEntry) error) *MockLedgerRepository_RecordDonation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLedgerRepository creates a new instance of MockLedgerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerRepository {
	mock := &MockLedgerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
