// Code generated by mockery v2.53.6. DO NOT EDIT.

package services

import (
	context "context"
	models "shb/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCompaignRepository is an autogenerated mock type for the CompaignRepository type
type MockCompaignRepository struct {
	mock.Mock
}

type MockCompaignRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompaignRepository) EXPECT() *MockCompaignRepository_Expecter {
	return &MockCompaignRepository_Expecter{mock: &_m.Mock}
}

// CreateCampaign provides a mock function with given fields: ctx, c
func (_m *MockCompaignRepository) CreateCampaign(ctx context.Context, c *models.MedicalCampaign) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateCampaign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MedicalCampaign) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCompaignRepository_CreateCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCampaign'
type MockCompaignRepository_CreateCampaign_Call struct {
	*mock.Call
}

// CreateCampaign is a helper method to define mock.On call
//   - ctx context.Context
//   - c *models.MedicalCampaign
func (_e *MockCompaignRepository_Expecter) CreateCampaign(ctx interface{}, c interface{}) *MockCompaignRepository_CreateCampaign_Call {
	return &MockCompaignRepository_CreateCampaign_Call{Call: _e.mock.On("CreateCampaign", ctx, c)}
}

func (_c *MockCompaignRepository_CreateCampaign_Call) Run(run func(ctx context.Context, c *models.MedicalCampaign)) *MockCompaignRepository_CreateCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.MedicalCampaign))
	})
	return _c
}

func (_c *MockCompaignRepository_CreateCampaign_Call) Return(_a0 error) *MockCompaignRepository_CreateCampaign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCompaignRepository_CreateCampaign_Call) RunAndReturn(run func(context.Context, *models.MedicalCampaign) error) *MockCompaignRepository_CreateCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllCampaigns provides a mock function with given fields: ctx, q
func (_m *MockCompaignRepository) GetAllCampaigns(ctx context.Context, q models.CampaignListQuery) (*models.CampaignPage, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCampaigns")
	}

	var r0 *models.CampaignPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CampaignListQuery) (*models.CampaignPage, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CampaignListQuery) *models.CampaignPage); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CampaignPage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CampaignListQuery) error); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompaignRepository_GetAllCampaigns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllCampaigns'
type MockCompaignRepository_GetAllCampaigns_Call struct {
	*mock.Call
}

// GetAllCampaigns is a helper method to define mock.On call
//   - ctx context.Context
//   - q models.CampaignListQuery
func (_e *MockCompaignRepository_Expecter) GetAllCampaigns(ctx interface{}, q interface{}) *MockCompaignRepository_GetAllCampaigns_Call {
	return &MockCompaignRepository_GetAllCampaigns_Call{Call: _e.mock.On("GetAllCampaigns", ctx, q)}
}

func (_c *MockCompaignRepository_GetAllCampaigns_Call) Run(run func(ctx context.Context, q models.CampaignListQuery)) *MockCompaignRepository_GetAllCampaigns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CampaignListQuery))
	})
	return _c
}

func (_c *MockCompaignRepository_GetAllCampaigns_Call) Return(_a0 *models.CampaignPage, _a1 error) *MockCompaignRepository_GetAllCampaigns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompaignRepository_GetAllCampaigns_Call) RunAndReturn(run func(context.Context, models.CampaignListQuery) (*models.CampaignPage, error)) *MockCompaignRepository_GetAllCampaigns_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCompaignRepository) GetByID(ctx context.Context, id int) (*models.MedicalCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.MedicalCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.MedicalCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.MedicalCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.MedicalCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompaignRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCompaignRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCompaignRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCompaignRepository_GetByID_Call {
	return &MockCompaignRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCompaignRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockCompaignRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCompaignRepository_GetByID_Call) Return(_a0 *models.MedicalCampaign, _a1 error) *MockCompaignRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompaignRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*models.MedicalCampaign, error)) *MockCompaignRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCampaignDetails provides a mock function with given fields: ctx, id
func (_m *MockCompaignRepository) GetCampaignDetails(ctx context.Context, id int) (*models.PublicCampaign, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaignDetails")
	}

	var r0 *models.PublicCampaign
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.PublicCampaign, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.PublicCampaign); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PublicCampaign)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCompaignRepository_GetCampaignDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaignDetails'
type MockCompaignRepository_GetCampaignDetails_Call struct {
	*mock.Call
}

// GetCampaignDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockCompaignRepository_Expecter) GetCampaignDetails(ctx interface{}, id interface{}) *MockCompaignRepository_GetCampaignDetails_Call {
	return &MockCompaignRepository_GetCampaignDetails_Call{Call: _e.mock.On("GetCampaignDetails", ctx, id)}
}

func (_c *MockCompaignRepository_GetCampaignDetails_Call) Run(run func(ctx context.Context, id int)) *MockCompaignRepository_GetCampaignDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockCompaignRepository_GetCampaignDetails_Call) Return(_a0 *models.PublicCampaign, _a1 error) *MockCompaignRepository_GetCampaignDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCompaignRepository_GetCampaignDetails_Call) RunAndReturn(run func(context.Context, int) (*models.PublicCampaign, error)) *MockCompaignRepository_GetCampaignDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockCompaignRepository) UpdateStatus(ctx context.Context, id int, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCompaignRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockCompaignRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - status string
func (_e *MockCompaignRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockCompaignRepository_UpdateStatus_Call {
	return &MockCompaignRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockCompaignRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id int, status string)) *MockCompaignRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *MockCompaignRepository_UpdateStatus_Call) Return(_a0 error) *MockCompaignRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCompaignRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, int, string) error) *MockCompaignRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCompaignRepository creates a new instance of MockCompaignRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompaignRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompaignRepository {
	mock := &MockCompaignRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
